= Week 1
Andrew Peel <andrew@andrewpeel.id.au>
:toc:

Of the Data Engineering Zoomcamp 2023.

{author} <{email}>


== Home work

=== Question 1

`+--iidfile string+` argument to `+docker build+` does "Write the image ID to the file".

=== Question 2

3 packages are installed in the python 3.9 docker image.

 $ docker run -it --entrypoint bash python:3.9

....
root@ac2771b102a5:/# pip list
Package    Version
---------- -------
pip        22.0.4
setuptools 58.1.0
wheel      0.38.4
....

=== Question 3

How many taxi trips were totally made on January 15?

20530.

....
root@localhost:nyc_taxi> SELECT COUNT(1) FROM green_taxi_trips WHERE DATE_TRUNC('day', lpep_pickup_datetime) = TIMESTAMP '2019-01-15' AND DATE_TRUNC('day', lpep_dropoff_datetime) = TIMESTAMP '2019-01-15';
+-------+
| count |
|-------|
| 20530 |
+-------+
SELECT 1
Time: 0.122s
....

=== Question 4

Which was the day with the largest trip distance? Use the pick up time for your calculations.

2019-01-15

....
root@localhost:nyc_taxi> select lpep_pickup_datetime from green_taxi_trips where trip_distance = (select max(trip_distance) from green_taxi_trips);
+----------------------+
| lpep_pickup_datetime |
|----------------------|
| 2019-01-15 19:27:58  |
+----------------------+
SELECT 1
Time: 0.126s
....

=== Question 5

In 2019-01-01 how many trips had 2 and 3 passengers?

1282 with two passengers, and 254 with 3 passengers.

....
root@localhost:nyc_taxi> select count(*) from green_taxi_trips where (date_trunc('day', lpep_pickup_datetime) = TIMESTAMP '2019-01-01' or date_trunc('day', lpep_dropoff_datetime) = TIMESTAMP '2019-01-01') AND passenger_count = 3;
+-------+
| count |
|-------|
| 254   |
+-------+
SELECT 1
Time: 0.072s
root@localhost:nyc_taxi> select count(*) from green_taxi_trips where (date_trunc('day', lpep_pickup_datetime) = TIMESTAMP '2019-01-01' or date_trunc('day', lpep_dropoff_datetime) = TIMESTAMP '2019-01-01') AND passenger_count = 2;
+-------+
| count |
|-------|
| 1282  |
+-------+
SELECT 1
Time: 0.077s
....

=== Question 6

For the passengers picked up in the Astoria Zone which was the drop up zone that had the largest tip? We want the name of the zone, not the id.

Long Island City/Queens Plaza.

....
root@localhost:nyc_taxi> select "Zone" from zones where "LocationID" = (select "DOLocationID" from green_taxi_trips where tip_amount = (select max(green_taxi_trips.tip_amount) from green_taxi_trips inner join zones on green_taxi_trips."PULocationID" = zones."LocationID" where zones."Zone" = 'Astoria'));
+-------------------------------+
| Zone                          |
|-------------------------------|
| Long Island City/Queens Plaza |
+-------------------------------+
SELECT 1
Time: 0.154s
....

== Ingesting the data


*In[32]:*
[source, ipython3]
----
import pandas as pd
----


*In[33]:*
[source, ipython3]
----
df = pd.read_csv("data/green_tripdata_2019-01.csv", nrows=10000)
----


*In[35]:*
[source, ipython3]
----
df.head(n=10)
----


*Out[35]:*
[cols=",,,,,,,,,,,,,,,,,,,,",options="header",]
|===
| |VendorID |lpep_pickup_datetime |lpep_dropoff_datetime
|store_and_fwd_flag |RatecodeID |PULocationID |DOLocationID
|passenger_count |trip_distance |fare_amount |extra |mta_tax |tip_amount
|tolls_amount |ehail_fee |improvement_surcharge |total_amount
|payment_type |trip_type |congestion_surcharge
|0 |2 |2018-12-21 15:17:29 |2018-12-21 15:18:57 |N |1 |264 |264 |5 |0.00
|3.0 |0.5 |0.5 |0.00 |0.0 |NaN |0.3 |4.30 |2 |1 |NaN

|1 |2 |2019-01-01 00:10:16 |2019-01-01 00:16:32 |N |1 |97 |49 |2 |0.86
|6.0 |0.5 |0.5 |0.00 |0.0 |NaN |0.3 |7.30 |2 |1 |NaN

|2 |2 |2019-01-01 00:27:11 |2019-01-01 00:31:38 |N |1 |49 |189 |2 |0.66
|4.5 |0.5 |0.5 |0.00 |0.0 |NaN |0.3 |5.80 |1 |1 |NaN

|3 |2 |2019-01-01 00:46:20 |2019-01-01 01:04:54 |N |1 |189 |17 |2 |2.68
|13.5 |0.5 |0.5 |2.96 |0.0 |NaN |0.3 |19.71 |1 |1 |NaN

|4 |2 |2019-01-01 00:19:06 |2019-01-01 00:39:43 |N |1 |82 |258 |1 |4.53
|18.0 |0.5 |0.5 |0.00 |0.0 |NaN |0.3 |19.30 |2 |1 |NaN

|5 |2 |2019-01-01 00:12:35 |2019-01-01 00:19:09 |N |1 |49 |17 |1 |1.05
|6.5 |0.5 |0.5 |0.00 |0.0 |NaN |0.3 |7.80 |1 |1 |NaN

|6 |2 |2019-01-01 00:47:55 |2019-01-01 01:00:01 |N |1 |255 |33 |1 |3.77
|13.5 |0.5 |0.5 |0.00 |0.0 |NaN |0.3 |14.80 |1 |1 |NaN

|7 |1 |2019-01-01 00:12:47 |2019-01-01 00:30:50 |N |1 |76 |225 |1 |4.10
|16.0 |0.5 |0.5 |0.00 |0.0 |NaN |0.3 |17.30 |1 |1 |NaN

|8 |2 |2019-01-01 00:16:23 |2019-01-01 00:39:46 |N |1 |25 |89 |1 |7.75
|25.5 |0.5 |0.5 |0.00 |0.0 |NaN |0.3 |26.80 |1 |1 |NaN

|9 |2 |2019-01-01 00:58:02 |2019-01-01 01:19:02 |N |1 |85 |39 |1 |3.68
|15.5 |0.5 |0.5 |0.00 |0.0 |NaN |0.3 |16.80 |1 |1 |NaN
|===


*In[36]:*
[source, ipython3]
----
my_dtypes = df.dtypes.apply(lambda x: x.name).to_dict()
----


*In[37]:*
[source, ipython3]
----
my_dtypes
----


*Out[37]:*
----
{'VendorID': 'int64',
 'lpep_pickup_datetime': 'object',
 'lpep_dropoff_datetime': 'object',
 'store_and_fwd_flag': 'object',
 'RatecodeID': 'int64',
 'PULocationID': 'int64',
 'DOLocationID': 'int64',
 'passenger_count': 'int64',
 'trip_distance': 'float64',
 'fare_amount': 'float64',
 'extra': 'float64',
 'mta_tax': 'float64',
 'tip_amount': 'float64',
 'tolls_amount': 'float64',
 'ehail_fee': 'float64',
 'improvement_surcharge': 'float64',
 'total_amount': 'float64',
 'payment_type': 'int64',
 'trip_type': 'int64',
 'congestion_surcharge': 'float64'}
----


*In[38]:*
[source, ipython3]
----
df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
----

Read the CSV file without writing it to the DB to check for any type
mismatches or other bad data.


*In[39]:*
[source, ipython3]
----
df_iter = pd.read_csv("data/green_tripdata_2019-01.csv", iterator=True, chunksize=100, dtype=my_dtypes)
----


*In[40]:*
[source, ipython3]
----
row = 0
try:
    for df in df_iter:
        df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
        df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)
        row += len(df)
except ValueError:
    print("row={}".format(row))
    raise
----


*In[41]:*
[source, ipython3]
----
row
----


*Out[41]:*
----
630918
----

Success! All of the rows were read without warnings. `wc -l` reported
630919 lines.

Now insert the data into the DB.


*In[43]:*
[source, ipython3]
----
import time
----


*In[45]:*
[source, ipython3]
----
from sqlalchemy import create_engine
----


*In[46]:*
[source, ipython3]
----
engine = create_engine("postgresql://root:root@localhost:5432/nyc_taxi")
----


*In[47]:*
[source, ipython3]
----
engine.connect()
----


*Out[47]:*
----
<sqlalchemy.engine.base.Connection at 0x7f50455b52a0>
----


*In[44]:*
[source, ipython3]
----
df_iter = pd.read_csv("data/green_tripdata_2019-01.csv", iterator=True, chunksize=100000, dtype=my_dtypes)
----


*In[48]:*
[source, ipython3]
----
for df in df_iter:
    start_time = time.time()
    df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)
    df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)
    df.to_sql(name="green_taxi_trips", con=engine, if_exists="append")
    print("Block time = {}".format(time.time() - start_time))
----


*Out[48]:*
----
Block time = 14.32096815109253
Block time = 12.706214904785156
Block time = 12.45663833618164
Block time = 12.27332329750061
Block time = 13.18382215499878
Block time = 12.71210503578186
Block time = 3.9592208862304688
----

Now load the taxi zone table.


*In[49]:*
[source, ipython3]
----
df = pd.read_csv("data/taxi_zone_lookup.csv")
----


*In[50]:*
[source, ipython3]
----
df.head(n=10)
----


*Out[50]:*
[cols=",,,,",options="header",]
|===
| |LocationID |Borough |Zone |service_zone
|0 |1 |EWR |Newark Airport |EWR
|1 |2 |Queens |Jamaica Bay |Boro Zone
|2 |3 |Bronx |Allerton/Pelham Gardens |Boro Zone
|3 |4 |Manhattan |Alphabet City |Yellow Zone
|4 |5 |Staten Island |Arden Heights |Boro Zone
|5 |6 |Staten Island |Arrochar/Fort Wadsworth |Boro Zone
|6 |7 |Queens |Astoria |Boro Zone
|7 |8 |Queens |Astoria Park |Boro Zone
|8 |9 |Queens |Auburndale |Boro Zone
|9 |10 |Queens |Baisley Park |Boro Zone
|===


*In[51]:*
[source, ipython3]
----
df.to_sql(name="zones", con=engine)
----


*Out[51]:*
----
265
----
